<?php

namespace ProfsCode\Nilvera\Facades;

use Illuminate\Support\Facades\Facade;

/**
 * @method static self debug(bool $state = true)
 * @method static array mapToModel(array $data, bool $isArchive = false)
 * @method static array getCredits()
 * @method static array checkTaxNumber(string $vkn)
 * @method static array getGlobalCustomerInfo(string $vkn)
 * @method static array getCustomerDetails(string $vkn)
 * @method static array getCompanyInfo()
 * @method static array updateCompanyInfo(array $data)
 * @method static array getCompanyModules()
 * @method static array getCompanyCertificates()
 * @method static bool addCompanyCertificate(array $data)
 * @method static bool updateCompanyCertificate(array $data)
 * @method static array getCompanyCertificateBySerial(string $serialNumber)
 * @method static bool deleteCompanyCertificate(int $id)
 * @method static array getUserCompanies()
 * @method static array getCompanyIdentities()
 * @method static array addCompanyIdentity(string $name, string $value)
 * @method static bool deleteCompanyIdentity(int $id)
 * @method static array getCampaigns()
 * @method static array getGibUserCredentials()
 * @method static bool updateGibUserCredentials(string $username, string $password)
 * @method static array getMailSettings()
 * @method static bool setWhatsappSetting(bool $isActive)
 * @method static bool setMailSetting(bool $isActive)
 * @method static bool setSmsSetting(bool $isActive)
 * @method static array getExchangeRates()
 * @method static array getLastInvoices(int $pageSize = 10, int $pageIndex = 1)
 * @method static array getLastSaleInvoices(string $mode = 'einvoice', int $pageSize = 10, int $pageIndex = 1)
 * @method static array getPurchaseDailyStats(string $startDate, string $endDate)
 * @method static array getSaleDailyStats(string $startDate, string $endDate, string $mode = 'einvoice')
 * @method static array getPurchaseSummaryStats(string $startDate, string $endDate)
 * @method static array getSaleSummaryStats(string $startDate, string $endDate, string $mode = 'einvoice')
 * @method static array getSeries(string $mode = 'einvoice', ?string $search = null, int $pageSize = 100, int $page = 1)
 * @method static array|string createSeries(string $name, string $mode = 'einvoice', bool $isActive = true, bool $isDefault = false)
 * @method static bool updateSeries(int $id, ?bool $isActive = null, ?bool $isDefault = null, string $mode = 'einvoice')
 * @method static array getSeriesDetail(int $id, string $mode = 'einvoice')
 * @method static array|string createCustomer(array $payload) // payload: ['TaxNumber' => string, 'Title' => string, 'Email' => string, 'City' => string, ...]
 * @method static array getCustomers(?string $search = null, int $pageSize = 30, int $page = 1, ?string $sortColumn = null, ?string $sortType = null)
 * @method static bool updateCustomer(array $data)
 * @method static array getCustomerById(int $id)
 * @method static bool deleteCustomer(int $id)
 * @method static bool bulkDeleteCustomers(array $ids)
 * @method static array searchCustomers(string $searchText)
 * @method static array getCustomerByTaxNumber(string $taxNumber)
 * @method static array getStocks(?string $search = null, int $pageSize = 30, int $page = 1, ?string $sortColumn = null, ?string $sortType = null, ?bool $isActive = null)
 * @method static array|string createStocks(array $payload)
 * @method static bool updateStock(array $data)
 * @method static array getStockById(int $id)
 * @method static bool deleteStock(int $id)
 * @method static bool bulkDeleteStocks(array $ids)
 * @method static array searchStocks(string $searchText)
 * @method static array createReport(array $data)
 * @method static array getReports(?string $search = null, int $pageSize = 30, int $page = 1, ?string $startDate = null, ?string $endDate = null, ?string $reportType = null)
 * @method static array downloadReport(string $uuid)
 * @method static array createReportTemplate(array $data)
 * @method static array getReportTemplates()
 * @method static array|string getTemplates(string $mode = 'einvoice', array $params = [])
 * @method static bool updateTemplate(int $id, ?string $name = null, ?bool $isActive = null, ?bool $isDefault = null, string $mode = 'einvoice')
 * @method static array getTemplateDetail(int $id, string $mode = 'einvoice')
 * @method static bool deleteTemplate(int $id, string $mode = 'einvoice')
 * @method static mixed previewTemplate(string $uuid, string $mode = 'einvoice')
 * @method static array getDraftInvoices(string $mode = 'einvoice', array $params = [])
 * @method static mixed getInvoiceHtml(string $uuid, string $mode = 'einvoice', ?string $direction = null)
 * @method static array getInvoiceAttachments(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array getInvoiceDetails(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array getInvoiceDespatchInfo(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array getInvoiceHistories(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array getInvoiceTaxes(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array|string answerInvoice(string $uuid, string $answerCode, ?string $rejectNote = null, string $mode = 'einvoice')
 * @method static array|string getInvoiceRejectedNote(string $uuid, string $mode = 'einvoice')
 * @method static array getInvoiceStatus(string $uuid, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static string|null exportInvoices(array $uuids, string $format = 'Pdf', string $direction = 'Sale')
 * @method static string|null getInvoicePdf(string $uuid, string $mode = 'einvoice')
 * @method static array createDraft(array $model, string $mode = 'einvoice')
 * @method static mixed previewInvoice(array $model, string $mode = 'einvoice')
 * @method static mixed downloadInvoice(array $model, string $mode = 'einvoice')
 * @method static mixed downloadInvoicePdf(array $model, string $mode = 'einvoice')
 * @method static array|string sendInvoiceBase64(string $zipFileBase64, string $alias, ?string $templateUuid = null, string $mode = 'einvoice')
 * @method static mixed previewInvoiceBase64(string $zipFileBase64, string $alias, string $mode = 'einvoice')
 * @method static array sendNewInvoice(array $model, string $mode = 'einvoice')
 * @method static array sendInvoice(string $uuid, ?string $alias = null, string $mode = 'einvoice')
 * @method static array bulkSendInvoices(array $invoices, string $mode = 'einvoice')
 * @method static array bulkDeleteInvoices(array $uuids, string $mode = 'einvoice')
 * @method static array getDraftModel(string $uuid, string $mode = 'einvoice')
 * @method static array getEditInvoiceData(string $uuid, string $mode = 'einvoice')
 * @method static array uploadXml(string $filePath, string $fileName, string $mode = 'einvoice')
 * @method static array createBulkDraft(array $invoices, string $mode = 'earchive')
 * @method static array uploadSgkPdf(string $filePath, string $fileName, string $type = 'SAGLIK_ECZ', string $registerCode = '')
 * @method static array getInvoices(string $direction = 'Sale', array $params = [])
 * @method static array getTags(string $mode = 'einvoice')
 * @method static array updateTags(string $uuid, array $tags, string $status = 'Draft', string $mode = 'einvoice')
 * @method static array|string createTag(string $name, ?string $description = null, ?string $color = null, string $mode = 'einvoice')
 * @method static bool updateTag(string $uuid, ?string $name = null, ?string $description = null, ?string $color = null, string $mode = 'einvoice')
 * @method static bool deleteTag(string $uuid, string $mode = 'einvoice')
 * @method static array getSaleNotificationSettings(string $mode = 'einvoice')
 * @method static array getPurchaseNotificationSettings(string $mode = 'einvoice')
 * @method static array|string createSaleNotificationSetting(array $data, string $mode = 'einvoice')
 * @method static array|string createPurchaseNotificationSetting(array $data, string $mode = 'einvoice')
 * @method static bool updateSaleNotificationSetting(array $data, string $mode = 'einvoice')
 * @method static bool updatePurchaseNotificationSetting(array $data, string $mode = 'einvoice')
 * @method static bool deleteSaleNotificationSetting(int $id, string $mode = 'einvoice')
 * @method static bool deletePurchaseNotificationSetting(int $id, string $mode = 'einvoice')
 * @method static array archiveInvoices(array $uuids, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array createDraftFromInvoices(array $uuids, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array updateSpecialCode($uuids, string $specialCode, string $mode = 'einvoice', string $direction = 'Sale')
 * @method static array markAsTransferred(array $uuids, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array markAsUntransferred(array $uuids, string $direction = 'Sale', string $mode = 'einvoice')
 * @method static array markAsRead(array $uuids, string $direction = 'Purchase', string $mode = 'einvoice')
 * @method static array markAsUnread(array $uuids, string $direction = 'Purchase', string $mode = 'einvoice')
 * @method static array updateDraftsStatus(array $uuids, string $operationType, string $mode = 'einvoice')
 * @method static array createReturnInvoice(string $uuid, string $direction = 'Purchase')
 * @method static array queryFromGib($uuids, string $direction = 'Sale')
 * @method static array getOldInvoices(string $mode = 'einvoice', array $params = [])
 * @method static mixed getOldInvoiceHtml(string $uuid, string $mode = 'einvoice')
 * @method static string|null getOldInvoicePdf(string $uuid, string $mode = 'einvoice')
 * @method static string|null getOldInvoiceXml(string $uuid, string $mode = 'einvoice')
 * @method static string|null exportOldInvoices(array $uuids, string $fileType = 'Pdf', string $mode = 'einvoice')
 * @method static array updateOldInvoicesStatus(array $uuids, string $operationType, string $mode = 'einvoice')
 * @method static array getEArchiveInvoices(array $params = [])
 * @method static array getGibInvoices(array $params = [])
 * @method static array cancelEArchiveInvoice(string $uuid)
 * @method static bool|array revertCancelEArchiveInvoice(string $uuid)
 * @method static array|string sendEArchiveReport(int $periodYear, int $periodMonth)
 * @method static array getEArchiveReports(int $pageSize = 30, int $page = 1, ?string $sortColumn = null, ?string $sortType = null, ?int $periodYear = null, ?int $periodMonth = null)
 * @method static array getEArchiveReportableDocuments(int $pageSize = 30, int $page = 1, ?string $search = null, ?int $periodYear = null, ?int $periodMonth = null)
 * @method static array getEArchiveReportDocuments(string $uuid, int $pageSize = 30, int $page = 1)
 * @method static mixed downloadEArchiveReportXml(string $uuid)
 * @method static array getEArchiveReportHistories(string $uuid)
 * @method static array sendWhatsapp(string $uuid, string $phone, string $mode = 'einvoice')
 * @method static array|string sendInvoiceEmail(string $uuid, array $emailAddresses)
 * @method static bool|array|string sendInvoiceSms(string $uuid, string $phone)
 * @method static array getMailActivityHistories(string $messageId)
 * @method static array getSmsHistories(string $uuid)
 * @method static array getWhatsappHistories(string $uuid)
 * @method static string|null getDraftXml(string $uuid, string $mode = 'einvoice')
 * @method static array getDashboardData(string $mode = 'einvoice', array $params = [])
 * @method static array getNewInvoiceData(string $mode = 'einvoice', string $type = 'service')
 *
 * @see \ProfsCode\Nilvera\Nilvera
 */
class Nilvera extends Facade
{
    protected static function getFacadeAccessor(): string
    {
        return 'nilvera';
    }
}
